export const GET_CURRENT_SONG_STARTED = 'GET_CURRENT_SONG_STARTED';
export const GET_CURRENT_SONG_FAILURE = 'GET_CURRENT_SONG_FAILURE';
export const GET_CURRENT_SONG_SUCCESS = 'GET_CURRENT_SONG_SUCCESS';

export const GET_LYRICS_STARTED = 'GET_LYRICS_STARTED';
export const GET_LYRICS_FAILURE = 'GET_LYRICS_FAILURE';
export const GET_LYRICS_SUCCESS = 'GET_LYRICS_SUCCESS';
